# Generated by Django 6.0.2 on 2026-03-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('repository', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(to='projects.skill')),
            ],
        ),
    ]
